Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Web.Data;

namespace Web.Controllers
{
    //[Authorize]
    public class AdminController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var productList = new List<ProductModel>();
            
            var productServiceClient = new ProductServiceClient();
            
            IAsyncEnumerator<ProductModel> products = productServiceClient.GetAllProducts();
            while (await products.MoveNextAsync())
            {
                productList.Add(products.Current);
            }
            await products.DisposeAsync();
            return View(productList);

        }

        public async Task<IActionResult> EditDelete(int id)
        {
            if(id != null)
            {
                 var productServiceClient = new ProductServiceClient();
            
            var product = await productServiceClient.GetProductById(id);
            
                if(product != null)
                {
                    return View(product);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductModel model)
        {
            if(ModelState.IsValid)
            {
                var productList = new List<ProductModel>();
                
                var productServiceClient = new ProductServiceClient();
                var prod = await productServiceClient.GetProductById(model.Id);
                if(prod !=null)
                {
                    var modelPost = prod;
                    modelPost.Name = model.Name;
                    modelPost.Price = model.Price;
                    modelPost.Description = model.Description;
                    modelPost.Category = model.Category;
                    modelPost.ProductImage = prod.ProductImage.Replace (Constants.blobUrl, "");
                    var response = await productServiceClient.UpdateProduct(modelPost);
                    if(response !=null)
                    {
                        
                        return RedirectToAction("Index");
                    }
                    else 
                    {
                        return RedirectToAction("Error"); 
                    }
                }
                else 
                {
                    return RedirectToAction("Error"); 
                }
            }
            else 
            {
                return RedirectToAction("Error"); 
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            if(id != null)
            {
                var productServiceClient = new ProductServiceClient();
            
                var product = await productServiceClient.DeleteProducts(id);
            
                if(product != null)
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Error");
        }
    }
}

Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using Web.Data;
using System.Web;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Session;


namespace Web.Controllers
{
    //[Authorize]
    public class CartController : Controller
    {
       
         private readonly string _cartItesmSessionKey = "CartItems";
         private readonly string _cartItemsCountSessionKey = "CartItemsCount";

        #region Methods

        // GET: /Cart/
        public IActionResult Index()
        {
             var cartItems = new List<CartItemModel>();

            // cartItems.Add(new CartItemModel(){
            //     Id = 1,
            //     Name = "Laptop",
            //     Price = 25000,
            //     OldPrice = 3000,
            //     Quantity = 1,
            //     MaxCartQuantity = 5,
            //     ProductImage = "/Images/asus gtx 1070 strix.png"
            // });
             if (HttpContext.Session.GetString(_cartItesmSessionKey) != null)
                cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(HttpContext.Session.GetString(_cartItesmSessionKey));
            return View(cartItems);
        }

        [Route("/Cart/Remove/{id}")]
        public async Task<IActionResult> Remove(int id)
        {
            if(id == null)
                return RedirectToAction("Index");
            // check if product exist
             var productServiceClient = new ProductServiceClient();
             var selectedItem = await productServiceClient.GetProductById(id);
             var cartItems = new List<CartItemModel>();
            if (HttpContext.Session.GetString(_cartItesmSessionKey) != null)
                cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(HttpContext.Session.GetString(_cartItesmSessionKey));
            
            if (cartItems.Exists(x => x.Id == selectedItem.Id))
                cartItems.RemoveAll(x=> x.Id == selectedItem.Id);

            //Remove from session
            HttpContext.Session.Remove(_cartItesmSessionKey);
            HttpContext.Session.Remove(_cartItemsCountSessionKey);

            HttpContext.Session.SetString(_cartItesmSessionKey, JsonConvert.SerializeObject(cartItems));
            HttpContext.Session.SetInt32(_cartItemsCountSessionKey, cartItems.Count());
            return RedirectToAction("Index");
        }

        //POST: /Cart/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int id)
        {
            if(id == null)
                return RedirectToAction("Index");

            // check if product exist
             var productServiceClient = new ProductServiceClient();
             var selectedItem = await productServiceClient.GetProductById(id);
            
            if(selectedItem == null)
                return RedirectToAction("Index");

            // check if there are already cart instance
            var cartItems = new List<CartItemModel>();
            if (HttpContext.Session.GetString(_cartItesmSessionKey) != null)
                cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(HttpContext.Session.GetString(_cartItesmSessionKey));

            // check if the item are already in the cart
            // if the item is already in the cart,
            // increase the quantity by 1
            if (cartItems.Exists(x => x.Id == selectedItem.Id))
                cartItems.Find(x => x.Id == selectedItem.Id).Quantity++;
            else
            {
                var item = new CartItemModel
                {
                    Id = selectedItem.Id,
                    Name = selectedItem.Name,
                    Price = selectedItem.Price,
                    ProductImage = selectedItem.ProductImage,
                    Quantity = 1
                };

                cartItems.Add(item);
            }

            // add to session
            HttpContext.Session.SetString(_cartItesmSessionKey, JsonConvert.SerializeObject(cartItems));
            HttpContext.Session.SetInt32(_cartItemsCountSessionKey, cartItems.Count());

            return RedirectToAction("Index");
        }

        //GET: /Cart/Checkout
        public async Task<IActionResult> Checkout(CartItemModel cartItem)
        {
            if(ModelState.IsValid)
            {
                var paymentServiceClient = new PaymentFunctionClient();
                var productServiceClient = new ProductServiceClient();
                var cartItems = new List<CartItemModel>();
                var products = new List<ProductModel>();
            if (HttpContext.Session.GetString(_cartItesmSessionKey) != null)
                cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(HttpContext.Session.GetString(_cartItesmSessionKey));

                var response = await paymentServiceClient.PayForProduct(cartItems);
                if(response !=null)
                {
                    cartItems.Clear();
                    HttpContext.Session.Remove(_cartItesmSessionKey);
                    HttpContext.Session.Remove(_cartItemsCountSessionKey);
                    ViewBag.Message = response;
                    products = JsonConvert.DeserializeObject<List<ProductModel>>(response);
                    var res = await productServiceClient.InsertHistory(products,"Buy");
                    
                    return View("PaymentSuccess");
                }
                else 
                {
                   return RedirectToAction("Error"); 
                }
            }
            else 
                {
                   return RedirectToAction("Error");  
                }

        }

        public async Task<IActionResult> PaymentSuccess(string message)
        {
            ViewBag.Message = message;
            return View();
        }


        #endregion
    }
}

Web/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Web.Data;

namespace Web.Controllers
{
    //[Authorize]
    public class HistoryController : Controller
    {
        // #region Fields

        #region Methods

        // GET: /History/
        public async Task<IActionResult> Index()
        {
             //var historyItems = new List<HistoryModel>();

            // if (Session.GetString(_cartItesmSessionKey) != null)
            //     cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(Session.GetString(_cartItesmSessionKey));
            // historyItems.Add(new HistoryModel(){
            //     Id = 1,
            //     Name = "Laptop",
            //     Price = 25000,
            //     Quantity = 1,
            //     ProductImage = "/Images/asus gtx 1070 strix.png",
            //     Action = "Buy",
            //     DateofPurchase = new DateTime(2020,1,24,0,0,0)
            // });
            // return View(historyItems);
            var historyList = new List<HistoryModel>();
            
            var productServiceClient = new ProductServiceClient();
            
            IAsyncEnumerator<HistoryModel> products = productServiceClient.GetHistory();
            while (await products.MoveNextAsync())
            {
                historyList.Add(products.Current);
            }
            await products.DisposeAsync();

            return View(historyList);
            
        }

       
        #endregion
    }
}

Web/Views/Shared/_CommonLayout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-Shopping</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.css" />
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
        <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a asp-area="" asp-controller="Home" asp-action="AllProducts" class= "btn btn-secondary"> View all items</a>
        <a asp-area="" asp-controller="History" asp-action="Index" class= "btn btn-secondary"> History</a>
        @* @if (User.IsInRole("Application administrator"))
        { *@
            <a asp-area="" asp-controller="Admin" asp-action="Index" class= "btn btn-secondary">Admin- Menu</a>
        @* } *@
        <a asp-area="" asp-controller="Home" asp-action="ProductAdd" class= "btn btn-secondary"> Sell Product</a>
        <a asp-area="" asp-controller="Cart" asp-action="Index" class= "btn btn-secondary"> View my Cart</a>
        
        <partial name="_LoginPartial" />
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <form asp-area="" asp-controller="Home" asp-action="ProductSearch" method="get" class="form-inline">
                        <input class="form-control mr-sm-2 my-1" name="name" placeholder="Search">
                        <button class="btn btn-outline-success my-1" type="submit">Search</button>
                    </form>
                </li>
            </ul>
        </div>
    </nav>
    <h1 style="background-color: aliceblue; vertical-align: middle;">Welcome to my shopping Website!!</h1>
     <div class="container-fluid">
        @RenderBody()
    </div>
     <section class="content-header clearfix">
                <div class="pull-left">
                    @await RenderSectionAsync("actionHeader", required: false)
                </div>
    </section>
    @if (User.IsInRole("Admin"))
    {
        <div class="open-admin" id="open-admin">
            <span class="fa fa-navicon">&nbsp;Admin</span>
        </div>

        <div class="admin-menu-body" id="admin-menu-body">
            <div class="close-admin">
                <span class="fa fa-close" id="close-admin"></span>
            </div>
            <div>
                <ul>
                    <li>
                        <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin dashboard</a>
                    </li>
                    @if (ViewData["ProductId"] != null)
                    {
                        <li>
                            <a asp-area="Admin" asp-controller="Product" asp-action="Edit" asp-route-id="@ViewData["ProductId"]">Edit product</a>
                        </li>
                    }
                    <li>
                        <a asp-area="Admin" asp-controller="Product" asp-action="List">Product Catalog</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Order" asp-action="List">Order List</a>
                    </li>
                </ul>
            </div>
        </div>
    }
    
    <br />
     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ECommerce website
        </div>
    </footer>
</body>
</html>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
<script>
    $(function () {
        if (JSON.parse(sessionStorage.getItem("isAdminMenuOpen")) === true) {
            document.getElementById("admin-menu-body").style.transition = "0s";
            document.getElementById("admin-menu-body").style.right = "0px";
        }
    });

    $(function () {
        $('#open-admin').on('click', function () {
            document.getElementById("admin-menu-body").style.right = "0px";
            sessionStorage.setItem("isAdminMenuOpen", JSON.stringify(true));
        });

        $('#close-admin').on('click', function () {
            document.getElementById("admin-menu-body").style.transition = "0.5s";
            document.getElementById("admin-menu-body").style.right = "-200px";
            sessionStorage.setItem("isAdminMenuOpen", JSON.stringify(false));
        });
    });
</script>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Welcome to E-Commerce Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <section class="content-header clearfix">
                <div class="pull-left">
                    @await RenderSectionAsync("actionHeader", required: false)
                </div>
    </section>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ECommerce website
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>